services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SYSTEM_PROMPT=${SYSTEM_PROMPT}
    volumes:
      - .:/app
    restart: unless-stopped 